version: "3.5"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=troquinhas
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_PORT=3306
    networks:
      - net-backend
  web:
    image: troquinhas/troquinhas:0.1
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - net-backend
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=teste
      - DATABASE_NAME=troquinhas
      - DATABASE_PORT=3306

networks:
  net-backend:
